# Here you can find docs bitnami/nginx chart https://github.com/bitnami/charts/blob/main/bitnami/nginx/README.md

image:
  registry: ghcr.io
  repository: tourmalinecore/pelican-cms
  tag: "latest"
  pullPolicy: Always
  debug: true

containerPorts:
  http: 1337
  https: ""

replicaCount: 1

# 1000m means 100% of processor time 
# 1m means 0.1% of processor time.
# at start pod is being allocated with resources from requests, if it needs more consumption can grow until limits.
# if pod uses more resources than limits in spite of the reason kube-system will perform a forced restart
resources:
  limits:
    cpu: 50m
    memory: 512Mi
  requests:
    cpu: 1m
    memory: 256Mi

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

service:
  type: ClusterIP
  ports:
    http: 1337
    https: ""

ingress:
  enabled: true
  hostname: "pelican.tourmalinecore.com"
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  ingressClassName: "nginx"
  tls:
    - hosts:
        - pelican.tourmalinecore.com
      secretName: pelican-tls
  rules:
    - host: pelican.tourmalinecore.com
      http:
        paths:
          - path: /cms/api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: strapi-service
                port:
                  number: 1337
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /api/$2

          - path: /cms(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: strapi-service
                port:
                  number: 1337
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /admin/$2

# not needed in this setup
serviceAccount:
  create: false

# not needed in this setup
networkPolicy:
  enabled: false
